// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB-grS89-IIB0tqrGVU8LSN7q4NnU1sENY',
    appId: '1:291505344960:web:27db1e7a3f6709e9acf825',
    messagingSenderId: '291505344960',
    projectId: 'tember-5a916',
    authDomain: 'tember-5a916.firebaseapp.com',
    storageBucket: 'tember-5a916.appspot.com',
    measurementId: 'G-K382LM4GHW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAsu1KlkiN-kK-LeHhMNuvm0Htxb5EeShM',
    appId: '1:291505344960:android:b0dba7fdae550fc5acf825',
    messagingSenderId: '291505344960',
    projectId: 'tember-5a916',
    storageBucket: 'tember-5a916.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfUjxBCEjjkRMmTRXdTMsQ-cV9b9v68ik',
    appId: '1:291505344960:ios:279a36f1926e3268acf825',
    messagingSenderId: '291505344960',
    projectId: 'tember-5a916',
    storageBucket: 'tember-5a916.appspot.com',
    iosBundleId: 'com.example.tember',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfUjxBCEjjkRMmTRXdTMsQ-cV9b9v68ik',
    appId: '1:291505344960:ios:35e832187254c06bacf825',
    messagingSenderId: '291505344960',
    projectId: 'tember-5a916',
    storageBucket: 'tember-5a916.appspot.com',
    iosBundleId: 'com.example.tember.RunnerTests',
  );
}
